[features]
seeds = false
[programs.devnet]
epic_project = "DbPM2jFTfuAuQnoXWLziSCNd7EqFurifx4rNZcBvbzo9"
# [programs.localnet]
# epic_project = "DbPM2jFTfuAuQnoXWLziSCNd7EqFurifx4rNZcBvbzo9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "/home/alexander/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
